import Testing
import Foundation
@testable import IrisKit

#if canImport(Tokenizers)
import Tokenizers

/// Verifies that swift-transformers tokenizes DeBERTa-v3 identically to the
/// Python `transformers` reference. This is the gating unknown for migrating the
/// Tier 2 CoreML guard from DistilBERT to `protectai/deberta-v3-base-prompt-injection-v2`:
/// DeBERTa-v3 uses a SentencePiece vocabulary, and if Swift produces different token
/// IDs than the model was traced against, the classifier silently misbehaves.
///
/// The fixture in `Fixtures/deberta-v3-tokenizer/` (tokenizer.json + tokenizer_config.json)
/// and the expected IDs (`expected_tokens.json`) are generated by
/// `AutoTokenizer.from_pretrained(...).save_pretrained(...)` with `add_special_tokens=True`,
/// matching exactly what `LiveCoreMLModel.evaluate(text:)` feeds the model.
@Suite("DeBERTa-v3 Tokenizer Parity")
struct DebertaV3TokenizerParityTests {

    struct ExpectedCase: Decodable {
        let text: String
        let ids: [Int]
    }

    struct Fixture: Decodable {
        let model: String
        let cls: Int
        let sep: Int
        let pad: Int
        let cases: [ExpectedCase]
    }

    /// Fixture directory, resolved relative to this source file so the test is
    /// self-contained and does not depend on `~/.iris` or network access.
    static var fixtureURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/deberta-v3-tokenizer")
    }

    static func loadFixture() throws -> Fixture {
        let data = try Data(contentsOf: fixtureURL.appendingPathComponent("expected_tokens.json"))
        return try JSONDecoder().decode(Fixture.self, from: data)
    }

    /// The multi-megabyte `tokenizer.json` vocab is gitignored; regenerate it with
    /// `scripts/gen_deberta_tokenizer_fixture.py`. Tests that actually load the tokenizer
    /// skip (rather than fail) when it is absent, so a fresh clone stays green.
    static var vocabPresent: Bool {
        FileManager.default.fileExists(atPath: fixtureURL.appendingPathComponent("tokenizer.json").path)
    }

    @Test("swift-transformers loads the DeBERTa-v3 tokenizer folder", .enabled(if: vocabPresent))
    func loadsTokenizer() async throws {
        // If swift-transformers cannot parse DeBERTa-v3's tokenizer.json, this throws,
        // and the migration is blocked at the tokenizer layer.
        _ = try await AutoTokenizer.from(modelFolder: Self.fixtureURL)
    }

    @Test("Special token IDs match the reference (CLS=1, SEP=2, PAD=0)")
    func specialTokensMatch() async throws {
        let fixture = try Self.loadFixture()
        #expect(fixture.cls == 1)
        #expect(fixture.sep == 2)
        #expect(fixture.pad == 0)
    }

    @Test("Encoded token IDs match the Python reference for real content", .enabled(if: vocabPresent))
    func encodingMatchesReference() async throws {
        let fixture = try Self.loadFixture()
        let tokenizer = try await AutoTokenizer.from(modelFolder: Self.fixtureURL)

        for testCase in fixture.cases {
            // Mirrors LiveCoreMLModel.evaluate(text:), which calls encode(text:) directly.
            let actual = tokenizer.encode(text: testCase.text)
            let mismatch = """
                Tokenization mismatch for \(String(reflecting: testCase.text)):
                  expected (Python): \(testCase.ids)
                  actual   (Swift):  \(actual)
                """

            if testCase.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                // Known, benign divergence: swift-transformers' UnigramTokenizer emits a
                // stray metaspace token for empty/whitespace-only input, whereas Python
                // drops it. Harmless for the guard (empty tool output is trivially safe),
                // but LiveCoreMLModel should still short-circuit empty input to 0.0.
                withKnownIssue("Empty/whitespace input diverges by one metaspace token; benign for the guard.") {
                    #expect(actual == testCase.ids, "\(mismatch)")
                }
            } else {
                #expect(actual == testCase.ids, "\(mismatch)")
            }
        }
    }
}
#endif
